# Generated by Django 5.2.8 on 2025-11-21 07:28

import django.db.models.deletion
import high_desert_happenings.hdh.models
import localflavor.us.models
import markdownx.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='ZIP Code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Website')),
                ('image', models.ImageField(blank=True, help_text='Location image', null=True, upload_to=high_desert_happenings.hdh.models.location_image_path, verbose_name='Image')),
                ('neighborhood', models.CharField(blank=True, choices=[('', ''), ('joshua-tree', 'Joshua Tree'), ('29-palms', '29 Palms'), ('wonder-valley', 'Wonder Valley'), ('pioneertown', 'Pioneertown'), ('landers', 'Landers'), ('yucca-valley', 'Yucca Valley'), ('morongo-valley', 'Morongo Valley'), ('mcagcc', '20 Palms Marine Corps Base')], max_length=30, verbose_name='Neighborhood')),
                ('dogs_allowed', models.BooleanField(blank=True, help_text='Check if dogs are allowed at this location', null=True, verbose_name='Dogs Allowed')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_locations', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', markdownx.models.MarkdownxField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Event image', null=True, upload_to='events/images/%Y/%m/', verbose_name='Image')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('webpage_url', models.URLField(blank=True, max_length=500, verbose_name='Webpage URL')),
                ('is_free', models.BooleanField(blank=True, help_text='Check if event is free to attend', null=True, verbose_name='Free Event')),
                ('age_restriction', models.CharField(blank=True, choices=[('children', 'Children'), ('21plus', '21+')], help_text='Age requirement for this event (blank = all ages)', max_length=10, verbose_name='Age Restriction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('series_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID identifying which events belong to the same recurring series', verbose_name='Series ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent_event', models.ForeignKey(blank=True, help_text='If this is a recurring event instance, reference to the parent event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_instances', to='hdh.event', verbose_name='Parent Event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='hdh.location', verbose_name='Location')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='hdh.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['series_id'], name='hdh_event_series__40e2cc_idx'), models.Index(fields=['start_datetime'], name='hdh_event_start_d_849c95_idx')],
            },
        ),
    ]
