# Generated by Django 5.2.8 on 2025-11-25 10:02

import high_desert_happenings.hdh.models
import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('children', 'Children'), ('21plus', '21+')], help_text='blank = all ages', max_length=10, verbose_name='Age Restriction'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Markdown is supported', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='webpage_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Event Link'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Location image', null=True, upload_to=high_desert_happenings.hdh.models.location_image_path, verbose_name='Event Image'),
        ),
    ]
