# Generated by Django 5.2.8 on 2025-11-20 07:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrences',
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='If this is a recurring event instance, reference to the parent event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_instances', to='hdh.event', verbose_name='Parent Event'),
        ),
        migrations.AddField(
            model_name='event',
            name='series_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID identifying which events belong to the same recurring series', verbose_name='Series ID'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['series_id'], name='hdh_event_series__40e2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_datetime'], name='hdh_event_start_d_849c95_idx'),
        ),
    ]
