volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  # production_traefik: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME}-django:main
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - '127.0.0.1:5000:5000'

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME}-postgres:main
    restart: unless-stopped
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  # traefik:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/traefik/Dockerfile
  #   image: ${REGISTRY}/${IMAGE_NAME}-traefik
  #   depends_on:
  #     - django
  #   volumes:
  #     - production_traefik:/etc/traefik/acme
  #   ports:
  #     - '0.0.0.0:80:80'
  #     - '0.0.0.0:443:443'

  redis:
    image: docker.io/redis:7.2
    restart: unless-stopped


  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    image: ${REGISTRY}/${IMAGE_NAME}-awscli:main
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
