volumes:
  high_desert_happenings_local_postgres_data: {}
  high_desert_happenings_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: high_desert_happenings_local_django
    container_name: high_desert_happenings_local_django
    depends_on:
      - postgres
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: high_desert_happenings_production_postgres
    container_name: high_desert_happenings_local_postgres
    volumes:
      - high_desert_happenings_local_postgres_data:/var/lib/postgresql/data
      - high_desert_happenings_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/awscli/Dockerfile
    image: high_desert_happenings_production_postgres_awscli
    env_file:
      - ./.envs/.production/.django
    volumes:
      - high_desert_happenings_local_postgres_data_backups:/backups
