#!/bin/sh

### List DB backups in Amazon S3 bucket
###
### Usage:
###     $ docker compose -f docker-compose.production.yml run --rm awscli list

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

export AWS_ACCESS_KEY_ID="${DJANGO_AWS_ACCESS_KEY_ID}"
export AWS_SECRET_ACCESS_KEY="${DJANGO_AWS_SECRET_ACCESS_KEY}"
export AWS_STORAGE_BUCKET_NAME="${DJANGO_AWS_STORAGE_BUCKET_NAME}"


aws s3 ls "s3://${AWS_STORAGE_BUCKET_NAME}${BACKUP_DIR_PATH}/"
